# centos-settings.yaml
# box_name: "gyptazy/centos9-arm64"
box_name: "sT0wn/kalilinux_arm64"
# box_version: "2.1.1"
box_version: "2025.2"
vm:
  - name: "kali-node01"
    ip: "172.16.32.222"
    memory: "4048"
    cpus: "4"
#  - name: "kali-node02"
#    ip: "192.168.201.12"
#    memory: "2048"
#    cpus: "2"
