//# centos-settings.yaml
# box_name: "gyptazy/centos9-arm64"
box_name: "centos9-arm64"
# box_version: "2.1.1"
box_version: "0"
vm:
  - name: "centos-controlplane"
    ip: "192.168.201.10"
    memory: "2048"
    cpus: "2"
  - name: "centos-node01"
    ip: "192.168.201.11"
    memory: "2048"
    cpus: "2"
  - name: "centos-node02"
    ip: "192.168.201.12"
    memory: "2048"
    cpus: "2"
