# debian-settings.yaml
# box_name: "gutehall/debian12"
box_name: "debian12-arm64"
box_version: "0"
vm:
- name: "debian-controlplane"
  ip: "192.168.201.10"
  memory: "2048"
  cpus: "2"
- name: "debian-node01"
  ip: "192.168.201.11"
  memory: "2048"
  cpus: "2"
- name: "debian-node02"
  ip: "192.168.201.12"
  memory: "2048"
  cpus: "2"
